name: make release
on:
  push:
    branches:
      main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: depndencies
      run: pip3 install lxml && git submodule init && git submodule update

    - name: makeFP
      run: python3 makeFP.py

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ver-${{ steps.date.outputs.date }}
        name: ${{ steps.date.outputs.date }}